name: Scala CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

permissions:
  contents: read

jobs:
  build:
    permissions:
      contents: 'read'
      id-token: 'write'

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - id: auth
      name: Authenticate with Google Cloud
      uses: google-github-actions/auth@v0
      with:
        token_format: access_token
        workload_identity_provider: projects/922529842459/locations/global/workloadIdentityPools/my-pool/providers/my-provider
        service_account: github-actions-service-account@orangutan-363612.iam.gserviceaccount.com
        access_token_lifetime: 300s
    - name: Login to Artifact Registry
      uses: docker/login-action@v1
      with:
        registry: europe-north1-docker.pkg.dev
        username: oauth2accesstoken
        password: ${{ steps.auth.outputs.access_token }}
    - name: Set up JDK 11
      uses: actions/setup-java@v3
      with:
        java-version: '11'
        distribution: 'temurin'
        cache: 'sbt'
    - name: Publish Docker image
      run: sbt docker:publish
    # - id: docker-push-tagged
    #   name: Tag Docker image and push to Google Artifact Registry
    #   uses: docker/build-push-action@v2
    #   with:
    #     push: true
    #     tags: |
    #         europe-north1-docker.pkg.dev/orangutan-363612/orangutan/orangutan-game:latest
